# =========================================================================
# VDA5050 CommAdapter ??
# =========================================================================
# MQTT Broker ? IP ?? (??????????? 127.0.0.1)
commadapter.vehicle.vda5050.mqtt.brokerHost=127.0.0.1
# MQTT Broker ???
commadapter.vehicle.vda5050.mqtt.brokerPort=1883
# ?? MQTT ???? Client ID
commadapter.vehicle.vda5050.mqtt.clientId=openTCS-Kernel
# MQTT ??? (????????)
commadapter.vehicle.vda5050.mqtt.username=
# MQTT ?? (????????)
commadapter.vehicle.vda5050.mqtt.password=
# ??????(ms)
commadapter.vehicle.vda5050.mqtt.keepAliveInterval=60000
